package springapp.web.model;
// Generated Feb 24, 2015 9:42:12 PM by Hibernate Tools 4.3.1



/**
 * PayRates generated by hbm2java
 */
public class PayRates  implements java.io.Serializable {


     private int idPayRates;
     private String payRateName;
     private long value;
     private long taxPercentage;
     private int payType;
     private long payAmount;
     private long ptLevelC;

    public PayRates() {
    }

    public PayRates(int idPayRates, String payRateName, long value, long taxPercentage, int payType, long payAmount, long ptLevelC) {
       this.idPayRates = idPayRates;
       this.payRateName = payRateName;
       this.value = value;
       this.taxPercentage = taxPercentage;
       this.payType = payType;
       this.payAmount = payAmount;
       this.ptLevelC = ptLevelC;
    }
   
    public int getIdPayRates() {
        return this.idPayRates;
    }
    
    public void setIdPayRates(int idPayRates) {
        this.idPayRates = idPayRates;
    }
    public String getPayRateName() {
        return this.payRateName;
    }
    
    public void setPayRateName(String payRateName) {
        this.payRateName = payRateName;
    }
    public long getValue() {
        return this.value;
    }
    
    public void setValue(long value) {
        this.value = value;
    }
    public long getTaxPercentage() {
        return this.taxPercentage;
    }
    
    public void setTaxPercentage(long taxPercentage) {
        this.taxPercentage = taxPercentage;
    }
    public int getPayType() {
        return this.payType;
    }
    
    public void setPayType(int payType) {
        this.payType = payType;
    }
    public long getPayAmount() {
        return this.payAmount;
    }
    
    public void setPayAmount(long payAmount) {
        this.payAmount = payAmount;
    }
    public long getPtLevelC() {
        return this.ptLevelC;
    }
    
    public void setPtLevelC(long ptLevelC) {
        this.ptLevelC = ptLevelC;
    }




}


